name: tela_apresentacao_pratico
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/minha_foto.jpg
    - assets/programacao.jpg
    - assets/jogos.jpg
    - assets/flutter.jpg
    - assets/projetos.jpg
    - assets/americana.jpg